"""
Briefing renderer.

Takes structured opportunities from the orchestrator and renders Markdown.
Designed to render readably on a phone (Telegram/WhatsApp via OpenClaw) and
in the Lovable webapp.
"""

from __future__ import annotations

from datetime import datetime, timezone
from typing import Any


def render_briefing(
    category: str, country: str, opportunities: list[dict[str, Any]]
) -> str:
    today = datetime.now(timezone.utc).strftime("%a %b %d, %Y")
    lines: list[str] = [
        f"# 📊 TrendStrike briefing — {today}",
        f"**Category:** {category}  •  **Region:** {country}",
        "",
    ]

    if not opportunities:
        lines.extend(
            [
                "_No opportunities passed the commercial-signal threshold today._",
                "",
                "This is a signal too — your category looks saturated or quiet right now. "
                "Try widening the category description, or check back tomorrow.",
            ]
        )
        return "\n".join(lines)

    lines.append(
        f"**{len(opportunities)} opportunities surfaced.** Ranked by signal strength."
    )
    lines.append("")

    for i, opp in enumerate(opportunities, 1):
        title = opp.get("title", "Untitled opportunity")
        signal = opp.get("signal_strength", "?")
        watch = opp.get("momentum_watch", False)
        badge = " 🔁 _momentum watch_" if watch else ""
        lines.append(f"## {i}. {title}{badge}")
        lines.append(
            f"**Signal:** {signal}/10  •  **Price band:** {opp.get('price_band', 'unclear')}"
        )
        lines.append("")

        why = opp.get("why_now")
        if why:
            lines.append(f"**Why now:** {why}")
            lines.append("")

        evidence = opp.get("evidence") or []
        if evidence:
            lines.append("**Evidence:**")
            for e in evidence:
                lines.append(f"- {e}")
            lines.append("")

        comp = opp.get("top_competitors") or []
        if comp:
            lines.append(f"**Existing sellers:** {', '.join(str(c) for c in comp)}")
            lines.append("")

        action = opp.get("recommended_action")
        if action:
            lines.append(f"**▶ Recommended action:** {action}")
            lines.append("")

        videos = opp.get("source_videos") or []
        if videos:
            lines.append("**Source videos:**")
            for v in videos[:3]:
                lines.append(f"- {v}")
            lines.append("")

        lines.append("---")
        lines.append("")

    lines.append(
        "_Generated by TrendStrike. Run again tomorrow to see what's changed._"
    )
    return "\n".join(lines)
