"""
Email delivery for TrendStrike briefings.

Sends the briefing as a polished HTML email via Resend. Designed to look
like a real morning newsletter a TikTok Shop seller would actually open —
not raw markdown dumped into a <pre> tag.

Failure mode: if Resend is unreachable or the API key is missing, we log
and continue. Email is a nice-to-have delivery channel; the briefing is
already saved in the Apify KV store and pushed to the Dataset regardless.
"""

from __future__ import annotations

import os
from datetime import datetime, timezone
from typing import Any

import resend

# ============================================================================
# HTML rendering
# ============================================================================

# Email-safe CSS: inline styles, no flexbox grid, table-friendly. We use a
# single dark-mode card stack because every modern email client (Gmail,
# Apple Mail, Outlook) renders this reliably.

_HTML_TEMPLATE = """\
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<title>TrendStrike briefing</title>
</head>
<body style="margin:0;padding:0;background:#0a0a0b;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Inter,sans-serif;color:#e8e8e8;">
<table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#0a0a0b;">
  <tr><td align="center" style="padding:32px 16px;">
    <table width="600" cellpadding="0" cellspacing="0" border="0" style="max-width:600px;width:100%;">

      <!-- Header -->
      <tr><td style="padding:0 0 24px 0;">
        <div style="font-size:11px;letter-spacing:2px;color:#ff6b35;text-transform:uppercase;font-weight:600;">TrendStrike</div>
        <div style="font-size:28px;font-weight:700;color:#ffffff;margin-top:8px;">Daily briefing</div>
        <div style="font-size:14px;color:#888;margin-top:4px;">{date} • {category} • {country}</div>
      </td></tr>

      <!-- Lead-in -->
      <tr><td style="padding:0 0 24px 0;font-size:15px;line-height:1.6;color:#bdbdbd;">
        <strong style="color:#ffffff;">{count} opportunities surfaced today.</strong>
        Ranked by signal strength. Each tied to a specific product, price band, and a recommended action you can take this week.
      </td></tr>

      <!-- Cards -->
      {cards}

      <!-- Footer -->
      <tr><td style="padding:32px 0 0 0;border-top:1px solid #222;">
        <div style="font-size:12px;color:#666;line-height:1.6;">
          Generated by TrendStrike — autonomous TikTok Shop opportunity agent.<br>
          Built on Apify. Runs daily. <a href="{actor_url}" style="color:#ff6b35;text-decoration:none;">View on Apify Store →</a>
        </div>
      </td></tr>

    </table>
  </td></tr>
</table>
</body>
</html>
"""


_CARD_TEMPLATE = """\
<tr><td style="padding:0 0 16px 0;">
  <table width="100%" cellpadding="0" cellspacing="0" border="0" style="background:#141416;border:1px solid #222;border-radius:6px;">
    <tr><td style="padding:24px;">

      <!-- Title row -->
      <table width="100%" cellpadding="0" cellspacing="0" border="0">
        <tr>
          <td style="vertical-align:top;">
            <span style="font-family:'JetBrains Mono',Menlo,monospace;font-size:14px;color:#666;">{rank:02d}</span>
            <span style="font-size:18px;font-weight:700;color:#ffffff;margin-left:8px;">{title}</span>
            {watch_badge}
          </td>
          <td style="text-align:right;vertical-align:top;width:100px;">
            <div style="font-family:'JetBrains Mono',Menlo,monospace;font-size:12px;color:#ff6b35;font-weight:600;">{signal}/10</div>
            <div style="font-size:10px;color:#666;letter-spacing:1px;text-transform:uppercase;margin-top:2px;">SIGNAL</div>
          </td>
        </tr>
      </table>

      <!-- Meta line -->
      <div style="margin-top:12px;font-size:13px;color:#888;">
        <span style="background:#222;padding:3px 8px;border-radius:3px;font-size:11px;">{category}</span>
        <span style="font-family:'JetBrains Mono',Menlo,monospace;color:#bdbdbd;margin-left:12px;">{price_band}</span>
      </div>

      <!-- Why now -->
      <div style="margin-top:16px;font-size:14px;line-height:1.6;color:#bdbdbd;font-style:italic;">
        {why_now}
      </div>

      <!-- Evidence -->
      <div style="margin-top:16px;">
        <div style="font-size:10px;color:#666;letter-spacing:1.5px;text-transform:uppercase;font-weight:600;margin-bottom:8px;">EVIDENCE</div>
        <ul style="margin:0;padding:0 0 0 18px;font-size:13px;line-height:1.7;color:#e8e8e8;">
          {evidence_items}
        </ul>
      </div>

      <!-- Action -->
      <div style="margin-top:20px;padding:14px 16px;background:#1c1c1e;border-left:3px solid #ff6b35;">
        <div style="font-size:10px;color:#ff6b35;letter-spacing:1.5px;text-transform:uppercase;font-weight:600;margin-bottom:4px;">▶ ACTION</div>
        <div style="font-size:13px;line-height:1.6;color:#ffffff;">{action}</div>
      </div>

      <!-- Sources -->
      <div style="margin-top:16px;font-size:11px;color:#666;">
        <span style="letter-spacing:1px;text-transform:uppercase;">Sources:</span>
        {source_links}
      </div>

    </td></tr>
  </table>
</td></tr>
"""


def _render_card(rank: int, opp: dict[str, Any]) -> str:
    watch = opp.get("momentum_watch", False)
    watch_badge = (
        '<span style="font-size:10px;color:#ff6b35;background:#2a1810;padding:2px 6px;border-radius:3px;margin-left:8px;letter-spacing:1px;">🔁 MOMENTUM</span>'
        if watch
        else ""
    )

    evidence = opp.get("evidence", []) or []
    evidence_html = "\n".join(
        f'<li style="margin-bottom:6px;">{e}</li>' for e in evidence
    )

    sources = opp.get("source_videos", []) or []
    source_html = "  ".join(
        f'<a href="{s}" style="color:#888;text-decoration:underline;margin-right:8px;">link {i+1}</a>'
        for i, s in enumerate(sources[:3])
    )

    return _CARD_TEMPLATE.format(
        rank=rank,
        title=_escape_html(opp.get("title", "Untitled")),
        signal=opp.get("signal_strength", "?"),
        category=_escape_html(opp.get("category", "—")),
        price_band=_escape_html(opp.get("price_band", "?")),
        why_now=_escape_html(opp.get("why_now", "")),
        evidence_items=evidence_html,
        action=_escape_html(opp.get("recommended_action", "—")),
        source_links=source_html or '<span style="color:#444;">no source links</span>',
        watch_badge=watch_badge,
    )


def _escape_html(text: Any) -> str:
    """Minimal HTML escape — we trust our own briefing text but defensively encode."""
    if not isinstance(text, str):
        text = str(text)
    return text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")


def render_briefing_html(
    category: str,
    country: str,
    opportunities: list[dict[str, Any]],
    actor_url: str = "https://apify.com",
) -> str:
    """Render the full HTML email body."""
    today = datetime.now(timezone.utc).strftime("%a %b %d, %Y")
    cards = "\n".join(_render_card(i + 1, opp) for i, opp in enumerate(opportunities))
    return _HTML_TEMPLATE.format(
        date=today,
        category=_escape_html(category),
        country=_escape_html(country),
        count=len(opportunities),
        cards=cards or "<tr><td>(no opportunities surfaced today)</td></tr>",
        actor_url=actor_url,
    )


# ============================================================================
# Sending
# ============================================================================


async def send_briefing_email(
    category: str,
    country: str,
    opportunities: list[dict[str, Any]],
    log: Any,
    actor_url: str = "https://apify.com",
) -> bool:
    """Send the briefing as an HTML email via Resend.

    Returns True if sent, False if skipped or failed. Never raises — email
    is a nice-to-have, the briefing already lives in Apify KV/Dataset.
    """
    api_key = os.environ.get("RESEND_API_KEY")
    to_email = os.environ.get("TRENDSTRIKE_EMAIL_TO")
    from_email = os.environ.get("TRENDSTRIKE_EMAIL_FROM", "onboarding@resend.dev")

    if not api_key:
        log.info("[email] RESEND_API_KEY not set — skipping email delivery")
        return False
    if not to_email:
        log.info("[email] TRENDSTRIKE_EMAIL_TO not set — skipping email delivery")
        return False

    resend.api_key = api_key
    today = datetime.now(timezone.utc).strftime("%a %b %d")
    top_pick = opportunities[0]["title"] if opportunities else "no opportunities"
    subject = f"📊 TrendStrike — {today} — {top_pick}"

    html = render_briefing_html(category, country, opportunities, actor_url)

    try:
        result = resend.Emails.send(
            {
                "from": f"TrendStrike <{from_email}>",
                "to": [to_email],
                "subject": subject,
                "html": html,
            }
        )
        log.info("[email] sent to %s (id=%s)", to_email, result.get("id", "?"))
        return True
    except Exception as e:
        log.warning("[email] send failed: %s", e)
        return False
